name: Build, Test, and Deploy

on:
  push:
    branches: [ "main", "dev", "organisation_bdd" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/checkout@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Ensure pytest and its plugins are installed
        pip install pytest pytest-faker cryptography bcrypt python-dotenv sqlalchemy

    - name: Run tests
      env:
        ENCRYPTION_KEY: "I6XWGKxqoi1qR-U6ugTjav7Jf6T0sMr5o_rEPKAW9Lo="
        HASH_STATIC_SALT: "Detection-en-temps-reel-avec-webcam-et-image-to-text"
        PYTHONPATH: .
      run: |
        pytest database/tests/